# Site settings
title: auricio Urraco
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mauricio Urraco
user_description: Joven, responsable, comprometido y decidido. En búsqueda de la contaste innovación como método para la toma de decisiones. Particular interés por la aplicación e impacto de la tecnología en la sociedad. La metodología aplicada a lo largo de mi educación, orientada a la acción, me ha permitido desarrollar una gran capacidad crítica y de resolución de conflictos.

user_title: Licenciado en Administración y Sistemas
email: joacoportela798@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
